### ISSUE TITLE
Problem with flavor surfix

### ISSUE THREAD

**Issue by cramer86** [nodes-android/kotlin-template#2]
When adding a new activity if the flavor is setup with a surfix, the imports generated will be wrong.

**Comment by johsoe** [comment]
Can you give me some more info? What did it generate, what should it generate?

**Comment by cramer86** [comment]
if you have a surfix in staging flavor.
then you generate a new class, let's call it test.
the imports generated in the activity will reference as ....staging.R and .staging.App
instead of the none surfix name
